### ISSUE TITLE
sysaudio: `floatToSigned` panics when passing samples outside range [-1,1]

### ISSUE THREAD

**Issue by menduz** [hexops/mach#1043]
Hi, I've found some issues on windows using sysaudio, this particular one panics the application because a `1.001` float overflows an `i16`, do you say that's a check that should be done in the application? The in-famous audio clippinng would be trivial to implement both in the `.write(channel, sample)` function and on each project using sysaudio.. in any case, debugging this issue required a ton of work because windows doesn't provide stack traces unless you use a debugger, and if clipping is at the end of the day necessary, we could handle it on the library to prevent the zig panic.

https://github.com/menduz/mach-sysaudio/commit/f1a42f7fecdf07a51b84feb2f8a692dc3cf54b0c

~Maybe this is an underlying issue, but even though we ask for a `format=f32` player, the wasapi is still creating a `i16` one.~ This is confirmed not an issue, in my windows setup there are only `i16` devices.

If you are interested in my solution, I've fixed the issue using the [std.math.tanh(sample)](https://www.mathworks.com/help/matlab/ref/tanh.html) function to ensure a soft-clipping and to enable adding channels as much as needed. Here is an interesting link where I took a lot of information from https://stackoverflow.com/questions/50436323/what-is-correct-way-to-add-audio-samples-into-the-one-without-clipping.

**Comment by slimsag** [comment]
Thanks for filing this. There are a few issues here, which will require multiple PRs to resolve:

* [ ] The non-type-conversion logic in `fn write` needs to be directly inlined inside `fn writeAll` - and we need to verify `self.writeStep();` is marked inline for performance in debug builds where the optimizer is likely not smart enough to inline.
* [ ] The entire type conversion logic (the whole `switch (self.format())` block) needs to be lifted out into a helper function which we can unit test. We need unit tests for its _current, existing/unchanged_ behavior.
* [ ] We need a new unit test which shows the case you are describing so we can determine if it is the expected behavior, or not. If it is expected, we need to document expectations of the write API properly.

I feel confident in saying that per-sample clipping is not the right answer, that would be very bad for performance and better handled at a higher level where you are producing samples.

However, that doesn't mean this isn't a bug in the type conversion logic (that switch statement which needs unit tests) - it's hard to say for sure from the issue description alone, though.
