### ISSUE TITLE
math: rename Scalar to Element

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#1047]
I've seen a few people get confused by Scalar

**Comment by pdoane** [comment]
I would get confused by Element :). Element implies a relationship to a container/vector.  E.g. seeing `quat.mulElement(5.0)` I'd wonder where the other object is, or which element of quat is being multiplied.

What's the confusion?

**Comment by noisegul** [comment]
Personally I also much prefer _scalar_ since with it everything stays more in line with mathematical definitions and the way LA is reasoned about. So here it made/makes things unambiguous and clearer to me than e.g. _element_. I can however see the argument being made for other names, since in (game)dev not everyone comes from such a background.

**Comment by slimsag** [comment]
ok, Scalar it is then :)
