### ISSUE TITLE
crazy, shouldn't you announce that you are LGBT when the Democratic Party is in power? ,why is  trump 

### ISSUE THREAD

**Issue by Super1Windcloud** [hexops/mach#1300]

**Comment by slimsag** [comment]
I see from your profile that you're clearly not a native English speaker - so I'll give you the benefit of the doubt. Besides, if it was with ill-intent that would place you among just 1% of over a few hundred coworkers and peers so far - surely your intention is not to join that minority group 😉

As an American, I have a constitutional right to be who I am and express myself freely. The 1st Amendment to our constitution protects my right to speak the truth as I see fit, and the 2nd Amendment ensures I can protect myself and my loved ones with deadly force from violence and government tyranny. These aren't just rights, they're responsibilities - standing up for LGBTQ+ rights, especially in challenging times, is part of upholding the fundamental American value of individual liberty and equal protections.

I came out because I am American, I have the right to do so, and I care about protecting other fellow Americans' rights. In America, we don't aim to hide who we are when times get tough - we become more visible, because that's what freedom is.

This issue tracker is for technical questions, however - so do not misuse it in the future or you will be banned.
