### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#18]
look into how to make this process nice, a unified app/window creation API, etc.

**Comment by guidorice** [comment]
@slimsag  I think it's promising not just for games but for cross-platform graphics of every kind. 👍🏽 

Re: "Browser implementation of gpu.Interface", I am curious if you are planning to use [Emscripten](https://emscripten.org) to build the Javascript <-> WASM glue code? I think that's the only way, currently, because in browser, only Javascript exposes the WebGPU driver.

Also it seems there is definitely interest in using WebGPU for General Purpose GPU (Compute), across native platforms, in browser, and in WASI as well. Some related links, which might provide some ideas for more bespoke things involving shader pipelines etc

* https://tvm.apache.org/2020/05/14/compiling-machine-learning-to-webassembly-and-webgpu
* https://github.com/WebAssembly/WASI/issues/285
