### ISSUE TITLE
gpu: build idiomatic Zig interface to WebGPU, abstract away native+browser support

### ISSUE THREAD

**Issue by slimsag** [hexops/mach#21]
This would give us a truly nice, cross-platform, seamless graphics API across browsers, mobile and desktop via Vulkan, Metal, and OpenGL as fallback.

Use the same Zig API for:

* WebAssembly (browser's implementation)
* Mobile ([dawn](https://dawn.googlesource.com/dawn) or [gfx-rs/wgpu-native](https://github.com/gfx-rs/wgpu-native) backend, at your choosing)
* Desktop ([dawn](https://dawn.googlesource.com/dawn) or [gfx-rs/wgpu-native](https://github.com/gfx-rs/wgpu-native) backend, at your choosing)

This is also the only truly cross-platform graphics API being blessed by major vendors (e.g. Apple) which leads me to believe it has a real shot long-term at displacing the tried and true Vulkan+Metal+OpenGL combo. And even if it doesn't, there has been a massive undertaking to offer a unified API of that Vulkan+Metal+OpenGL combo in forming WebGPU that very few will be able to effectively beat in the general case (e.g. I think we can effectively beat Godot's, potentially Unity and Unreal's, graphics API abstractions using WebGPU.)

**Comment by slimsag** [comment]
Sent a PR to fix the Obj-C++ compilation issue in Zig: https://github.com/ziglang/zig/pull/10096

**Comment by meshula** [comment]
Sorry I missed your reply, if you post a branch, I'm definitely interested.

**Comment by slimsag** [comment]
@meshula Cool! You indeed found the branch I'm working from, https://github.com/hexops/mach/pull/62 is the pull request which has more details on how to use it, issues, etc. I probably need about a day more before it'll be relatively easy for you to try running it

**Comment by meshula** [comment]
I got all the way to the compiling .mm issue, as you might expect. I haven't been building zig myself, so does it make sense to wait for that to land? or is there an artifact I can download from CI somewhere?

I have a fairly large contraption right now where I am writing zig bindings over my LabSlang project, which I need for a current zig project that currently is CLI only. I'd be happy to shift my attention to mach in the short term to see if we are both pushing in the same direction. Due to the mm compilation issue, I can do other things in the meanwhile and wait a little for "relatively easy", and therefore put off learning to build zig :)

**Comment by meshula** [comment]
The only part of the build that required a bit of research was the installation of git-subtree. I downloaded the git sources, and did an install from the contrib/subtree folder, with `make;sudo make -prefix=/XXX install` where XXX is the path containing `bin/git`. Might be worth noting that twist for others who attempt it.

**Comment by slimsag** [comment]
@meshula can you clarify why you needed to install Git from source? AFAIK, only I myself should ever need to use `git subtree`, nobody else should ever need to.

I'd wait until I can get the `.mm` change landed, then Zig's CI will build artifacts for you.

**Comment by meshula** [comment]
Here's what I did.

1. clone mach
2. zig build (didn't work, glfw not found, grep build system discover pull-subrepos.sh)
3. cd dev;./pull-subrepos.sh (complains about subtree because of https://github.com/hexops/mach/blob/9f906cfd944a2dc9c5385a9e08231aa5c6f46521/dev/pull-subrepos.sh#L6
5. install git subtree as above, try pull-suprepos again (git loses it's mind, zomg)
6. delete mach; reclone
7. cd dev;/pull-subrepos.sh (succeeds)
8. cd ..;zig build (gets as far as mentioned)

I was making it up as I went along since I wasn't sure what the intended build process actually is, and I haven't used git in a monorepo context in this way before. Maybe I missed an obvious (to one practiced in the monorepo arts ;) ) workflow step.

**Comment by slimsag** [comment]
> zig build (didn't work, glfw not found,

I'd love more details on this part, what error did you get? GLFW is committed to the repository the same as any other file, so you really shouldn't have ever needed to touch `git subtree` at all. There isn't any magic here, `git subtree` just helps us with copying files back and forth between two repositories.

**Comment by meshula** [comment]
hmm, I think i have another mac without git subtree installed. standby.

**Comment by meshula** [comment]
ok, all of my macs except that one have subtree installed, so (1) there is likely something wrong with git on that machine, probably I've hacked it too much with aliases and helper things. (2) all my other machines function as you describe; I can clone and zig build in the root directory, and in the dawn branch, in the webgpu directory, with the same .mm issue.

All right, sorry for the noise, but glad to have worked through this.

**Comment by slimsag** [comment]
Perfect! Glad to hear it.
