### ISSUE TITLE
glfw: expose error functions publicly

### ISSUE THREAD

**Issue by mitchellh** [hexops/mach#586]
Background problem: I'm integrating glfw with Dear Imgui. The Dear Imgui GLFW integration explicitly states that it may cause errors on X11 systems and sets a null error handler to just black hole them. Even with a null error handler, `glfwGetError` will store and return the last error. When I initialize Dear Imgui, it swallows the errors, but still has the code set in glfw, and the next Mach glfw lib binding I call that calls `getError` panics in `unreachable` since its [typically] an unexpected error code.

My workaround for now is to manually extern and call "glfwGetError" and throw it away after Dear Imgui initialization. 

I'd like the `errors.zig` functions to be exposed publicly so I can call `glfw.getError`. 

Arguably, this is a bug in Dear Imgui and I might report it there too.

**Comment by mitchellh** [comment]
Also reported to Imgui, not sure if they will consider this a bug, though: https://github.com/ocornut/imgui/issues/5785

**Comment by slimsag** [comment]
Orthogonal: you might be interested to know https://github.com/machlibs/imgui exists, not sure if it helps you though (since it's on top of Mach core, not glfw.)

I'm happy to expose this by changing this line to public:

https://github.com/hexops/mach/blob/1cbef1f7e1129c5ca92409a5434892a4386fd99c/libs/glfw/src/main.zig#L11

This would make `glfw.errors.getError` and `glfw.errors.getErrorString` available to you, while hiding it behind a namespace to make it clear that most users probably shouldn't be using these functions.

**Comment by mitchellh** [comment]
Yeah that'd be great to expose it in case stuff like this happens again.

**Comment by mitchellh** [comment]
> Orthogonal: you might be interested to know https://github.com/machlibs/imgui exists, not sure if it helps you though (since it's on top of Mach core, not glfw.)

Just saw this! Thanks, but integrating imgui was pretty simple. I'm binding myself to cimgui so I can more easily keep it up to date but it took me less than an hour probably including all the C builds.

**Comment by michal-z** [comment]
@mitchellh Keep in mind that you will need C ABI workarounds for some functions in cimgui. Those are the workarounds that were needed for stage1: https://github.com/prime31/zig-gamekit/blob/main/gamekit/deps/imgui/temporary_hacks.cpp

One of the reasons I created zgui was to avoid those kind of issues.
