### ISSUE TITLE
mach-freetype readme instructions don't work in latest zig version

### ISSUE THREAD

**Issue by IntegratedQuantum** [hexops/mach#714]
## Reproduction
In the latest version of zig(`0.11.0-dev.1796+c9e02d3e6`) following the readme instructions fails:
```zig
	exe.addModule("freetype", freetype.module(b));
	exe.addModule("harfbuzz", freetype.harfbuzzModule(b));
	freetype.link(b, exe, .{ .harfbuzz = .{} });
```
error:
```
mach-freetype/src/main.zig:1:1: error: file exists in multiple modules
mach-freetype/src/main.zig:1:1: note: root of module root.harfbuzz.freetype
mach-freetype/src/main.zig:1:1: note: root of module root.freetype
```
## The problem
`freetype.harfbuzzModule(b)` internally also calls `freetype.module(b)`. This seems to yield two different identical `freetype` modules.
And apperently now zig seems to have a problem with that.
## Workaround
Here is a workaround I found, but I don't think it's ideal:
```zig

	const harfbuzzModule = freetype.harfbuzzModule(b);
	const freetypeModule = harfbuzzModule.dependencies.get("freetype").?;
	exe.addModule("harfbuzz", harfbuzzModule);
	exe.addModule("freetype", freetypeModule);
	freetype.link(b, exe, .{ .harfbuzz = .{} });
```

**Comment by dweiller** [comment]
This is a problem with more than just freetype - the same pattern is used in other libraries under `libs/`. A similar (or the same) issue happens when a module includes a file that the root file of an executable includes as well, which makes problems with `libs/core`.

**Comment by gf3** [comment]
i think it's related to this: https://github.com/ziglang/zig/issues/14708

from the suggested fix it seems like freetype will have to add a dependency on itself?

**Comment by mlugg** [comment]
This is somewhat funny, because I was originally motivated to make this compiler change due to a latent bug that specifically mach-freetype exposed.

The solution here is for the `Module` value to be memoized somehow. However, an even easier solution would be to just use the package manager; then the `freetype` and `harfbuzz` packages are defined in the same place, so you can set up the dependencies correctly.

@slimsag -- what's the status on switching Mach over to the package manager? Are there any big blockers? I'm happy to look into fixing this with the existing setup, but it'd be simpler to just use the package manager if possible. If that's just a matter of "you haven't gotten around to it", I might have some time to kill today so could have a look.

**Comment by slimsag** [comment]
In the latest `main` I've added memoization for the `Module` value, so this should be fixed now. You can use [the latest nightly Zig version as of right now listed here](https://github.com/hexops/mach/tree/d9bcb1e291a4d781ad1ff4ae3bb0c209674ef83f#supported-zig-version)

Totally agree with switching to the package manager ASAP; let's track that in https://github.com/hexops/mach/issues/721
