### ISSUE TITLE
glfw: Vulkan loading base handle panics in release

### ISSUE THREAD

**Issue by Avokadoen** [hexops/mach#99]
Inital issue was filed in the vulkan example as I though it was a bug in that code and can be found [here](https://github.com/hexops/mach-glfw-vulkan-example/issues/1)

The following will panic in release (but not in debug):
```zig
const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) vk.PfnVoidFunction, glfw.getInstanceProcAddress);
self.vkb = try BaseDispatch.load(vk_proc);
```
replacing the following code in mach-glfw resolves the issue:
vulkan.zig
```zig
pub fn getInstanceProcAddress(vk_instance: ?*opaque {}, proc_name: [*:0]const u8) callconv(.C) ?VKProc {
    const proc_address = c.glfwGetInstanceProcAddress(if (vk_instance) |v| @ptrCast(c.VkInstance, v) else null, proc_name);
    getError() catch |err| @panic(@errorName(err));
    if (proc_address) |addr| return addr;
    return null;
}
```
with 
```zig
pub const getInstanceProcAddress = c.glfwGetInstanceProcAddress;
```

**Comment by Avokadoen** [comment]
Since the mach wrapper doe snot really add any direct improvements, I vote for it to simply forward export of the function instead of having its own wrapper implementation. The only issue is that getError() will pollute other functions

**Comment by InKryption** [comment]
Which error(s) does it panic with? Is it 'ApiUnavailable'?

**Comment by Avokadoen** [comment]
> Which error(s) does it panic with? Is it 'ApiUnavailable'?
Included in the original issue: ``thread 1030138 panic: reached unreachable code``

**Comment by InKryption** [comment]
It's definitely a weird issue; your fix does stop the panic from happening, but removing the 'getError' call and catch also stops it. As well, when I run it with gdb, without the fix, it seems to panic before even calling `root.main`, instead panicking in 'start.zig', while measuring the `c_envp` parameter of `start.main`. On Windows 10 at least.

**Comment by Avokadoen** [comment]
Indeed, then we know the issue is cross platform as i tested on ubuntu 20.04. 

I'm am having issues other places in my code on release, so I am starting to suspect there might be some weird miss compilations in zig master.

**Comment by InKryption** [comment]
After flipping a bunch of knobs on and off, I've discovered what I believe to be the culprit: in 'graphics_context.zig', inside the function `GraphicsContext.init`, the line of code: 
```zig
const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) vk.PfnVoidFunction, glfw.getInstanceProcAddress);
```
It would seem that the issue here is to do with calling convention. By changing the line of code to:
```zig
const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) callconv(vk.vulkan_call_conv) vk.PfnVoidFunction, glfw.getInstanceProcAddress);
```
The panic no longer occurs, so it is very probable that the issue here is how the compiler is deciding to call the function that is calling all the weirdness.

**Comment by Avokadoen** [comment]
Tested and works. Good job! I'll close this issue, but keep the issue on the vulkan project.

**Comment by slimsag** [comment]
Thanks for reporting this and debugging! You are definitely right about the pointer cast missing a calling convention being the culprit here.

However, I want to call out that using `vk.vulkan_call_conv` is not right in this case. You should use `callconv(.C)` I believe as this is a GLFW C proc, not a Vulkan proc, as I described previously in https://github.com/hexops/mach/issues/49#issuecomment-955053903

Unfortunately, vulkan-zig does not declare `vk.PfnGetInstanceProcAddr` with the correct calling convention either, I have filed an issue: https://github.com/Snektron/vulkan-zig/issues/30

The most correct change I see, aside from fixing that issue in zig-vulkan, is the following:

```diff
-const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) vk.PfnVoidFunction, glfw.getInstanceProcAddress);
+const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) callconv(.C) vk.PfnVoidFunction, glfw.getInstanceProcAddress);
```

**Comment by InKryption** [comment]
Good point, I hadn't thought about that, and it just happened to work so my brain decided that "welp, our work here is done".

**Comment by Snektron** [comment]
> `pub fn getInstanceProcAddress(vk_instance: ?*opaque {}, proc_name: [*:0]const u8) callconv(.C) ?VKProc {`

> `const vk_proc = @ptrCast(fn(instance: vk.Instance, procname: [*:0]const u8) vk.PfnVoidFunction, glfw.getInstanceProcAddress);`

There is a calling convention mismatch here, `getInstanceProcAddress` is defined as having the C calling convention, while it's cast to a function pointer with the C calling convention. Note that the `load` function for Wrappers does not require any specific calling convention, specifically to allow you to load using functions that do not necessarily follow the Vulkan calling convention. Furthermore, the return value of whatever the loader returns is pointer-cast into the target function pointer type. Either what @slimsag suggested, or something along the lines of the following seem correct to me:
```zig
fn vkzGetInstanceProcAddr(instance: vk.Instance, proc_name: [*:0]const u8) vk.PfnVoidFunction {
  const glfw_vk_instance = switch (instance) {
    .null_handle => null,
    else => @intToPtr(?*glfw.OpaqueVkInstance, @enumToInt(instance)),
  };
  return @ptrCast(vk.PfnVoidFunction, glfw.getInstanceProcAddr(glfw_vk_instance, proc_name)); 
}
```
```
self.vkb = try BaseDispatch.load(vkzGetInstanceProcAddr);
```
